exercise migration and query builder
st-lynguyen/laravel-intern-2111 pull request #2
Opened 2021-12-21 11:56 UTC by st-lynguyen

exercise migration and query builder

2021-12-22 02:58 UTC, st-minhdao requested changes
Please check my comment~

2021-12-22 02:58 UTC, st-minhdao commented on layout_and_module_task/app/Http/Controllers/TaskController.php
> +        $actual = $request->actual;
những biến tạo ra chỉ dùng 1 lần thì mình ko nên khởi tạo đâu em, dùng trực tiếp nó cho phần insert ở dưới cũng dc

2021-12-22 02:58 UTC, st-minhdao commented on layout_and_module_task/app/Http/Controllers/TaskController.php
> +        $tasks = DB::table('tasks')->where('id', $id)->get();
function show chỉ show ra thông tin của 1 task thôi, em dùng get() là nó sẽ trả về array á, có thể dùng first hoặc find

2021-12-22 02:58 UTC, st-minhdao commented on layout_and_module_task/app/Http/Controllers/TaskController.php
> +        $tasks = DB::table('tasks')->where('id', $id)->get();
tương tự comment trên, em nên lấy ra 1 record thôi nha
tên biến thì sẽ là số ít $task

2021-12-22 02:58 UTC, st-minhdao commented on layout_and_module_task/app/Http/Controllers/TaskController.php
> +        $actual = $request->actual;
bỏ những biến chỉ khởi tạo và dùng 1 lần

2021-12-22 02:58 UTC, st-minhdao commented on layout_and_module_task/app/Http/Controllers/TaskController.php
> +        $task = DB::table('tasks')->where('id', $id)->get();
lấy dữ liệu của 1 task

2021-12-22 02:58 UTC, st-minhdao commented on layout_and_module_task/app/Http/Controllers/TaskController.php
> +        $users = DB::table('users')->where('email', '=', 'ali82@example.com')->exists();
hàm exists sẽ trả về giá trị true/false, em nên đặt lại tên biến để rõ nghĩa hơn, ví dụ như `$userExisted`

2021-12-22 02:58 UTC, st-minhdao commented on layout_and_module_task/app/Http/Requests/TaskRequest.php
> +            'status' => 'required|numeric',
số nguyên dương nha em

2021-12-22 02:58 UTC, st-minhdao commented on layout_and_module_task/app/Http/Requests/TaskRequest.php
> +            'estimate' => 'required|numeric',
chỗ này mình validate kiểu float(3, 1) thì sẽ chính xác hơn

2021-12-22 02:58 UTC, st-minhdao commented on layout_and_module_task/database/migrations/2021_12_20_073759_create_tasks_table.php
> +            $table->integer('status')->nullable();
kiểu int hơi lớn, e có thể dùng tinyInt và nó là số dương nha

2021-12-22 02:58 UTC, st-minhdao commented on layout_and_module_task/database/migrations/2021_12_20_073759_create_tasks_table.php
> +            $table->float('actual');
em sửa lại để chỉ nhận những số dạng `XX.Y` thử được không

2021-12-22 02:58 UTC, st-minhdao commented on layout_and_module_task/resources/views/admin/tasks/edit.blade.php
> +    @foreach ($tasks as $task)
vì ở trên em lấy ra mảng nên chỗ này màn hình edit mà lại phải for nè, check lại giúp anh nha, tương tự cho những màn hình khác

2021-12-22 05:19 UTC, st-trampham commented on layout_and_module_task/resources/views/admin/tasks.blade.php
> +                        </form>
<form> dùng cho route delete thôi, những route show với edit đưa ra khỏi form
Đưa file tasks.blade.php này vào trong folder admin/tasks luôn, có thể đổi lại tên file là index

2021-12-23 01:48 UTC, st-trampham commented on layout_and_module_task/app/Http/Controllers/TaskController.php
> +        $task = DB::table('tasks')->where('id', '=', '1')->get();
Dùng first() hoặc find() để lấy 1 record

2021-12-23 01:49 UTC, st-trampham commented on layout_and_module_task/app/Http/Controllers/TaskController.php
> +        $count = DB::table('tasks')->get()->count();
không cần `->get()` chỗ này

2021-12-23 02:01 UTC, st-trampham commented on layout_and_module_task/resources/views/admin/tasks/edit.blade.php
>              <input type="text" class="form-control" id="exampleFormControlInput1" name="assignee"
Chỗ này e đổi thành select tag chọn user

2021-12-23 02:09 UTC, st-trampham commented on layout_and_module_task/routes/web.php
>      Route::delete('/tasks/{id}', [TaskController::class, 'destroy'])->name('tasks.destroy');
Name Prefixes luôn e

2021-12-23 04:48 UTC, st-trampham commented
LGTM!

2021-12-23 04:48 UTC, merged