create practice_eloquent_orm
st-lynguyen/laravel-intern-2111 pull request #3
Opened 2021-12-24 08:40 UTC by st-lynguyen

create practice_eloquent_orm

2021-12-27 03:08 UTC, st-minhdao requested changes

2021-12-27 03:08 UTC, st-minhdao commented on layout_and_module_task/app/Repositories/UserRepository.php
> +    public function getIdAndName()
public function getUsers($columns)

2021-12-27 03:08 UTC, st-minhdao commented on layout_and_module_task/app/Http/Controllers/TaskController.php
> +        $users = $this->userRepository->getIdAndName();
$this->userRepository->getUsers(['id', 'name']);

2021-12-27 03:08 UTC, st-minhdao commented on layout_and_module_task/app/Repositories/UserRepository.php
> +        return User::select('id', 'name')->get();
return User::select($columns)->get();

2021-12-27 07:55 UTC, st-minhdao requested changes
please check my comment

2021-12-27 07:55 UTC, st-minhdao commented on layout_and_module_task/app/Http/Controllers/TaskController.php
> +        $users = $this->userRepository->getIdAndName();
truyền mảng là column muốn select để có thể tận dụng được function cho những chỗ khác nha Lý

2021-12-27 07:55 UTC, st-minhdao commented on layout_and_module_task/app/Http/Controllers/TaskController.php
> +        $this->taskRepository->createTask($request->all());
dùng request->validated() để dữ liệu chuẩn hơn

2021-12-27 07:55 UTC, st-minhdao commented on layout_and_module_task/app/Models/Task.php
> +    }
chỗ ni em remove đi, trong bài tập relationship thì tận dụng cái relationship để lấy dữ liệu

2021-12-27 07:55 UTC, st-minhdao commented on layout_and_module_task/app/Repositories/TaskRepository.php
> +        return Task::whereId($taskId)->update($newDetails);
tách ra 2 dòng lệnh giúp anh

2021-12-27 07:55 UTC, st-minhdao commented on layout_and_module_task/app/Repositories/UserRepository.php
> +    }
những function chưa dùng đến thì không cần phải implement

2021-12-27 07:55 UTC, st-minhdao commented on layout_and_module_task/database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->softDeletes();
tạo file migration mới để thực hiện việc thêm columns soft delete

2021-12-27 07:55 UTC, st-minhdao commented on layout_and_module_task/database/migrations/2021_12_20_073759_create_tasks_table.php
> +            $table->softDeletes();
tạo file migration mới

2021-12-28 02:21 UTC, st-trampham commented on layout_and_module_task/app/Http/Controllers/TaskController.php
> +    private UserRepositoryInterface $userRepository;
Chỗ này chỉ cần khai báo như này là dc
private $taskRepository;
private $userRepository;

2021-12-31 07:18 UTC, st-trampham commented
LGTM!

2021-12-31 07:19 UTC, merged